### PR TITLE
Add comment to setup timezone

### PR DESCRIPTION
**Pull request by jolcese**
If timezone is not added, daily energy calculations will wrap at. a wrong hour.

# What does this implement/fix?

Added configuration item to set proper timezone.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by clowrey** [comment]
You can also just use the Home Assistant time - that's what I do. 
https://esphome.io/components/time/homeassistant.html

**Comment by jolcese** [comment]
> You can also just use the Home Assistant time - that's what I do.

Thanks @clowrey! Where do you set up that on Home Assistant?
(Probably is still a good thing to add the right timezone to esphome)

**Comment by clowrey** [comment]
> > You can also just use the Home Assistant time - that's what I do.
> 
> Thanks @clowrey! Where do you set up that on Home Assistant? (Probably is still a good thing to add the right timezone to esphome)

As long as the correct time zone is set for your home assistant install it will be fine as it uses the same one.

**Comment by jolcese** [comment]
> As long as the correct time zone is set for your home assistant install it will be fine as it uses the same one.

Not in my case. I have properly set timezone in HA and still daily energy was wrapping at 4PM
ESPHome was reporting UTC and cut was at 4PM (I'm on GMT-8) so makes sense

**Comment by clowrey** [comment]
> > As long as the correct time zone is set for your home assistant install it will be fine as it uses the same one.
> 
> Not in my case. I have properly set timezone in HA and still daily energy was wrapping at 4PM ESPHome was reporting UTC and cut was at 4PM (I'm on GMT-8) so makes sense

But you were using the SNTP time module right? Same as the example config for emporia... That does need the time zone set. I'm saying that with the home assistant time module it is not needed - I think the maintainer should update the example to use the home assistant time module and then no one will have this issue again. 

Instead of 
time:
  - platform: sntp
    id: my_time

It should be:
time:
  - platform: homeassistant
    id: my_time

**Comment by jolcese** [comment]
Ok, that makes sense. Any of these 2 changes should fix it.

``` 
time: 
  - platform: homeassistant
    id: my_time

time: 
  - platform: sntp
    id: my_time
    timezone: 'America/Los_Angeles'
```

**Comment by clowrey** [comment]
Agreed :)

**Comment by flaviut** [comment]
`  - platform: sntp` gets the time zone [from the computer that you're building the project from:](https://esphome.io/components/time/index.html)

> ESPHome tries to automatically infer the time zone string based on the time zone of the computer that is running ESPHome, but this might not always be accurate.

For HomeAssistant, it also doesn't really matter when the daily energy usage resets. HomeAssistant can handle whatever happens.

`  - platform: sntp` also works for people who use this in a MQTT-only system.

Because of that, and because I've heard minimal complaints about this, I'd rather just leave the example as-is.

**Pull request closed without merging**
